dist: trusty

language: java

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel_0.24.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.24.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.24.1-linux-x86_64.deb

script:
  - bazel --bazelrc=tools/bazel.travis.rc build //src/main/...
  - bazel --bazelrc=tools/bazel.travis.rc test //src/test/...
